### ISSUE TITLE
NAs

### ISSUE THREAD

**Issue by pasichnyi** [corynissen/geocodeHERE#5]
Hello!
I wonder, if it's still usable, as I get NAs for any search strings (incl examples like "chicago")?
I tried both with and without app id/codes.

**Comment by corynissen** [comment]
HERE has shut down it's free service. It's free tier is only a 90 day trial. I haven't updated the code since they shut down the free tier.

**Comment by pasichnyi** [comment]
I see, thanks! Any other advises on free geocoding services (possible bundled with R)?

**Comment by corynissen** [comment]
ggmap::geocode uses google, I think.

**Comment by pasichnyi** [comment]
Thank you!
